### ISSUE TITLE
Getting error when Deploying Alertmananger

### ISSUE THREAD

**Issue by JohnMarszalek** [Thakurvaibhav/k8s#23]
I'm trying to deploy the Alertmanager onto a AWS EKS cluster, and it's erroring.  When I look at the logs, I get the following:

level=error ts=2020-05-26T20:50:56.287Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="unsupported scheme \"\" for URL"

Any ideas why this is happening?

**Comment by Thakurvaibhav** [comment]
@JohnMarszalek This is because the [receivers](https://prometheus.io/docs/alerting/configuration/) have not been configured in the your config file. 
Please go through the README [here](https://github.com/Thakurvaibhav/k8s/tree/master/monitoring#kubernetes-monitoring-and-alerting-in-less-than-5-minutes)

**Comment by JohnMarszalek** [comment]
@Thakurvaibhav I have tried running this with commenting out the receivers, as I do not want to push alerts to any system at this time, and still get a failure.  Are we required to use those receivers?

**Comment by Thakurvaibhav** [comment]
@JohnMarszalek In that case you should disable the alertmanager.

**Comment by Thakurvaibhav** [comment]
@JohnMarszalek I am closing this issue. Please let me know if you need any further help.
